### ISSUE TITLE
slog handler initialization panics

### ISSUE THREAD

**Issue by julian7** [dexidp/dex#3559]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

0b6a78397e2632bf844def79239a6322e565041b

### Storage Type

In-memory

### Installation Type

Binary

### Expected Behavior

example command runs with demo config

### Actual Behavior

example command panics on run

### Steps To Reproduce

1. clone repo
2. run `make bin/dex`
3. run `bin/dex serve examples/config-dev.yaml`
4. receive crash:

```text
panic: nil Handler

goroutine 1 [running]:
log/slog.New(...)
	/opt/homebrew/Cellar/go/1.22.3/libexec/src/log/slog/logger.go:154
main.newLogger(0x0, {0x0, 0x0})
	.../dex/cmd/dex/serve.go:534 +0x1ac
main.runServe({{0x16dc87476, 0x18}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}})
	.../dex/cmd/dex/serve.go:95 +0x22c
main.commandServe.func1(0x1400012e100?, {0x140000530b0?, 0x4?, 0x102fe2da1?})
	.../dex/cmd/dex/serve.go:67 +0x88
github.com/spf13/cobra.(*Command).execute(0x14000330f08, {0x14000053080, 0x1, 0x1})
	.../pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x14000330c08)
	.../pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	.../pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
	.../dex/cmd/dex/main.go:24 +0x20
```

### Additional Information

set `handler` variable before creating a new slog logger:

```diff
❯ git di -U8 | cat
diff --git cmd/dex/serve.go cmd/dex/serve.go
index b39354ec..456e07f6 100644
--- cmd/dex/serve.go
+++ cmd/dex/serve.go
@@ -515,21 +515,21 @@ func runServe(options serveOptions) error {
 }

 var logFormats = []string{"json", "text"}

 func newLogger(level slog.Level, format string) (*slog.Logger, error) {
 	var handler slog.Handler
 	switch strings.ToLower(format) {
 	case "", "text":
-		slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
+		handler = slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
 			Level: level,
 		})
 	case "json":
-		slog.NewJSONHandler(os.Stderr, &slog.HandlerOptions{
+		handler = slog.NewJSONHandler(os.Stderr, &slog.HandlerOptions{
 			Level: level,
 		})
 	default:
 		return nil, fmt.Errorf("log format is not one of the supported values (%s): %s", strings.Join(logFormats, ", "), format)
 	}

 	return slog.New(handler), nil
 }
```

/cc @seankhliao

**Comment by seankhliao** [comment]
🤦 ...

**Comment by nabokihms** [comment]
I'm going to open the PR because we are out of time for the next release. Sorry for the impatience.
